name: Build

on:
  push:
    branches:
      - master

  pull_request:

  workflow_dispatch:
    inputs:
      tags:
        description: "Tag Name"
        required: false

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci

      - name: Build Grammar from yaml to json
        run: npm run bg

      - name: build with webpack
        run: npm run webpackp

      - name: build with esbuild
        run: npm run esbuildp
