name: tsc compile

on:
  push:
    branches:
      - master

  pull_request:

  workflow_dispatch:
    inputs:
      tags:
        description: "Tag Name"
        required: false

jobs:
  tsc_compile:
    name: tsc compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci

      - name: tsc compile
        run: npm run tscc

      - name: tsc compile with declarationMap
        run: npm run tsccd
