name: vsce Publish

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
          tags:
            description: 'Tag Name'
            required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  #test:
  #  strategy:
  #    matrix:
  #      os: [macos-latest, ubuntu-latest, windows-latest]
  #  runs-on: ${{ matrix.os }}
  #  
  #  steps:
  #    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #    - uses: actions/checkout@v2
  #    
  #    - uses: actions/setup-node@v2
  #      with:
  #        node-version: 16
  #        
  #    - name: Install dependencies
  #      run: npm install
  #    
  #    # https://snyk.io/blog/vs-code-extension-building-auto-cicd-with-github-actions/
  #    - name: Run headless test
  #      uses: GabrielBB/xvfb-action@v1.0
  #      with:
  #        run: npm test

  publish:
    #needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      
      - name: run vsce publish
        run: npm run publish
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        
      - name: Archive vsix production
        uses: actions/upload-artifact@v3
        with:
          name: vsix production
          path: ./*.vsix
          if-no-files-found : error

      - name: print tag
        env:
          TAGS: ${{ github.event.inputs.tags }}
        run: |
          echo "[$TAGS] build completed."
